# Default values for mysql-workflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
restartPolicy: OnFailure

image:
  database: mysql:latest
  tier: database
  migrations: vetalb60/migrations:0.6

deployment:
  strategy:
    mysql: Recreate

database:
  port: 3306

container:
  port: 33333
  name: server

resources:
  storage: 1Gi

volume:
  mountPath: /var/lib/mysql

configmap:
  name: server-config
  namespace: default