// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteDeleteIDParams creates a new DeleteDeleteIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteDeleteIDParams() *DeleteDeleteIDParams {
	return &DeleteDeleteIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDeleteIDParamsWithTimeout creates a new DeleteDeleteIDParams object
// with the ability to set a timeout on a request.
func NewDeleteDeleteIDParamsWithTimeout(timeout time.Duration) *DeleteDeleteIDParams {
	return &DeleteDeleteIDParams{
		timeout: timeout,
	}
}

// NewDeleteDeleteIDParamsWithContext creates a new DeleteDeleteIDParams object
// with the ability to set a context for a request.
func NewDeleteDeleteIDParamsWithContext(ctx context.Context) *DeleteDeleteIDParams {
	return &DeleteDeleteIDParams{
		Context: ctx,
	}
}

// NewDeleteDeleteIDParamsWithHTTPClient creates a new DeleteDeleteIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteDeleteIDParamsWithHTTPClient(client *http.Client) *DeleteDeleteIDParams {
	return &DeleteDeleteIDParams{
		HTTPClient: client,
	}
}

/* DeleteDeleteIDParams contains all the parameters to send to the API endpoint
   for the delete delete ID operation.

   Typically these are written to a http.Request.
*/
type DeleteDeleteIDParams struct {

	// ID.
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete delete ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDeleteIDParams) WithDefaults() *DeleteDeleteIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete delete ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteDeleteIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete delete ID params
func (o *DeleteDeleteIDParams) WithTimeout(timeout time.Duration) *DeleteDeleteIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete delete ID params
func (o *DeleteDeleteIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete delete ID params
func (o *DeleteDeleteIDParams) WithContext(ctx context.Context) *DeleteDeleteIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete delete ID params
func (o *DeleteDeleteIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete delete ID params
func (o *DeleteDeleteIDParams) WithHTTPClient(client *http.Client) *DeleteDeleteIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete delete ID params
func (o *DeleteDeleteIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete delete ID params
func (o *DeleteDeleteIDParams) WithID(id int64) *DeleteDeleteIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete delete ID params
func (o *DeleteDeleteIDParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDeleteIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
