// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"exec/client/models"
)

// GetReader is a Reader for the Get structure.
type GetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOK creates a GetOK with default headers values
func NewGetOK() *GetOK {
	return &GetOK{}
}

/* GetOK describes a response with status code 200, with default header values.

returns a status
*/
type GetOK struct {
	Payload *models.Health
}

func (o *GetOK) Error() string {
	return fmt.Sprintf("[GET /][%d] getOK  %+v", 200, o.Payload)
}
func (o *GetOK) GetPayload() *models.Health {
	return o.Payload
}

func (o *GetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Health)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBadRequest creates a GetBadRequest with default headers values
func NewGetBadRequest() *GetBadRequest {
	return &GetBadRequest{}
}

/* GetBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetBadRequest struct {
	Payload *models.Error
}

func (o *GetBadRequest) Error() string {
	return fmt.Sprintf("[GET /][%d] getBadRequest  %+v", 400, o.Payload)
}
func (o *GetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetInternalServerError creates a GetInternalServerError with default headers values
func NewGetInternalServerError() *GetInternalServerError {
	return &GetInternalServerError{}
}

/* GetInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetInternalServerError struct {
	Payload *models.Error
}

func (o *GetInternalServerError) Error() string {
	return fmt.Sprintf("[GET /][%d] getInternalServerError  %+v", 500, o.Payload)
}
func (o *GetInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
