// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"exec/client/models"
)

// GetHealthzReader is a Reader for the GetHealthz structure.
type GetHealthzReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHealthzReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHealthzOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetHealthzBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetHealthzInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHealthzOK creates a GetHealthzOK with default headers values
func NewGetHealthzOK() *GetHealthzOK {
	return &GetHealthzOK{}
}

/* GetHealthzOK describes a response with status code 200, with default header values.

returns a status
*/
type GetHealthzOK struct {
	Payload *models.Health
}

func (o *GetHealthzOK) Error() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzOK  %+v", 200, o.Payload)
}
func (o *GetHealthzOK) GetPayload() *models.Health {
	return o.Payload
}

func (o *GetHealthzOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Health)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHealthzBadRequest creates a GetHealthzBadRequest with default headers values
func NewGetHealthzBadRequest() *GetHealthzBadRequest {
	return &GetHealthzBadRequest{}
}

/* GetHealthzBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetHealthzBadRequest struct {
	Payload *models.Error
}

func (o *GetHealthzBadRequest) Error() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzBadRequest  %+v", 400, o.Payload)
}
func (o *GetHealthzBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetHealthzBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHealthzInternalServerError creates a GetHealthzInternalServerError with default headers values
func NewGetHealthzInternalServerError() *GetHealthzInternalServerError {
	return &GetHealthzInternalServerError{}
}

/* GetHealthzInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetHealthzInternalServerError struct {
	Payload *models.Error
}

func (o *GetHealthzInternalServerError) Error() string {
	return fmt.Sprintf("[GET /healthz][%d] getHealthzInternalServerError  %+v", 500, o.Payload)
}
func (o *GetHealthzInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetHealthzInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}


