// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"exec/client/models"
)

// GetListReader is a Reader for the GetList structure.
type GetListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetListBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetListInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetListOK creates a GetListOK with default headers values
func NewGetListOK() *GetListOK {
	return &GetListOK{}
}

/* GetListOK describes a response with status code 200, with default header values.

returns a list
*/
type GetListOK struct {
	Payload models.Array
}

func (o *GetListOK) Error() string {
	return fmt.Sprintf("[GET /files][%d] getListOK  %+v", 200, o.Payload)
}
func (o *GetListOK) GetPayload() models.Array {
	return o.Payload
}

func (o *GetListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetListBadRequest creates a GetListBadRequest with default headers values
func NewGetListBadRequest() *GetListBadRequest {
	return &GetListBadRequest{}
}

/* GetListBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetListBadRequest struct {
	Payload *models.Error
}

func (o *GetListBadRequest) Error() string {
	return fmt.Sprintf("[GET /files][%d] getListBadRequest  %+v", 400, o.Payload)
}
func (o *GetListBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetListBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetListInternalServerError creates a GetListInternalServerError with default headers values
func NewGetListInternalServerError() *GetListInternalServerError {
	return &GetListInternalServerError{}
}

/* GetListInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetListInternalServerError struct {
	Payload *models.Error
}

func (o *GetListInternalServerError) Error() string {
	return fmt.Sprintf("[GET /files][%d] getListInternalServerError  %+v", 500, o.Payload)
}
func (o *GetListInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetListInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
