apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategy }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - image: {{ .Values.image.serverRepo }}
          name: {{ .Release.Name }}
          ports:
            - containerPort: {{ .Values.deployment.containers.port.server }}
              protocol: TCP
          env:
            - name: MYSQL_POD_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-pod-ip
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-database-name
            - name: MYSQL_PORT
              value: {{ .Values.deployment.containers.port.mysql | quote }}
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-database-user
            - name: MYSQL_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-table_name