apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations
spec:
  backoffLimit: 20
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-migrations
    spec:
      containers:
        - name: {{ .Release.Name }}-migrations
          image: {{ .Values.image.migrations }}
          ports:
            - containerPort: {{ .Values.container.port }}
              name: {{ .Values.container.name }}
          env:
            - name: MYSQL_POD_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-pod-ip
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-database-name
            - name: MYSQL_PORT
              value: {{ .Values.database.port | quote }}
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-database-user
            - name: MYSQL_TABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: mysql-table_name
      restartPolicy: {{ .Values.restartPolicy }}
