apiVersion: storage.helm.io/v1
kind: StorageClass
metadata:
  name: {{ .Release.Name }}-standard
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pv-claim
  labels:
    app: {{ .Release.Name }}
    tier: {{ .Values.image.tier }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.storage }}
